/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.3.0).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.hello.helloworldservice.api;

import com.hello.helloworldservice.model.HelloWorldMessage;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.Metrics;
import io.swagger.annotations.Api;
import io.swagger.v3.oas.annotations.*;
import io.swagger.v3.oas.annotations.media.*;
import io.swagger.v3.oas.annotations.responses.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Validated
@Api(value = "hola", description = "the hola API")
public interface HolaApi {

  default HolaApiDelegate getDelegate() {
    return new HolaApiDelegate() {};
  }

  /**
   * GET /hola : Hello World example Simple example service to say hello world
   *
   * @return Success (status code 200)
   */
  @Operation(
    operationId = "holaMundo",
    summary = "Hello World example",
    tags = {"hola"},
    responses = {
      @ApiResponse(responseCode = "200", description = "Success",
        content = {
          @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = HelloWorldMessage.class)
          )
        }
      )
    }
  )
  @RequestMapping(method = RequestMethod.GET, value = "/hola", produces = {"application/json"})
  default ResponseEntity<HelloWorldMessage> holaMundo() {

    Counter holaMundoCounter = Metrics.counter("HolaApi.holaMundo");
    holaMundoCounter.increment();
    return getDelegate().holaMundo();
  }
}
