kind: ConfigMap
apiVersion: v1
metadata:
  name: example-configmap
  namespace: spring-cloud-system
  labels:
    spring.cloud.kubernetes.config: "true"
  annotations:
    spring.cloud.kubernetes.configmap.apps: "helloworld-service"
data:
  features.newFeatureEnabled: "true"
